app = "moneyagario-api"

[build] Dockerfile = "backend/Dockerfile" context = "backend"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
