name: Deploy backend to Fly.io

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "backend/Dockerfile"
      - "fly.toml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --app moneyagario-api
